language: node_js
node_js:
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install
    - curl -X DELETE http://localhost:5984/cozy
    - pwd
    - forever start -o forever-ds.log server.js
    - ps aux | grep server.js
    - sudo netstat -plunt
    - sleep 5
    - cat forever-ds.log
    - curl http://localhost:9101/
    - cd ..
    - export NAME=home
    - export TOKEN=token
