language: node_js
node_js:
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system
    - npm install forever coffee-script -g
    - npm install
    - pwd
    - forever start server.js -o forever-ds.log
    - ps aux | grep server.js
    - netstat -plunt | grep 9101
    - sleep 5
    - cat forever-ds.log
    - curl http://localhost:9101/
    - cd ..
